const clean=(value,limit=4000)=>String(value??'').trim().slice(0,limit);
const key=value=>clean(value,500).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const list=value=>Array.isArray(value)?value:[];
const unique=value=>[...new Set(list(value).map(item=>clean(item,500)).filter(Boolean))];
const slug=value=>key(value).replace(/\s+/g,'-')||'configuration';
const object=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const numberOrNull=value=>value==null||value===''||!Number.isFinite(Number(value))?null:Math.max(0,Number(value));

export const MODE_SELECTION_POLICIES=Object.freeze(['CURRENT_ONLY','CHOOSE_BEFORE_ACTION']);
export const MODE_SWITCH_TYPES=Object.freeze(['PLAYER_SELECTED','AUTOMATIC','ABILITY_TRIGGERED','DAMAGE_TRIGGERED','DEATH_TRIGGERED','PHASE_TRIGGERED','GM_TRIGGERED','CONDITION_TRIGGERED']);

export function isModeContextAbility(ability={},role={}){
  if(ability.modeContextOnly===true||ability.selectableAsAction===false||String(ability.recordType||'').toUpperCase()==='MODE_CONTEXT')return true;
  const name=clean(ability.name,300),roleName=clean(role.name,200);
  if(!/\b(?:mode|form|state|phase|stance|configuration)\b/i.test(name))return false;
  return Boolean(roleName)&&key(name).startsWith(key(roleName)+' ');
}

function normalizeSwitchRules(value={}){
  const source=object(value),type=String(source.type??source.switchType??source.switch_type??'PLAYER_SELECTED').toUpperCase(),cooldown=clean(source.cooldown??source.switchCooldown??source.switch_cooldown,500),inferredCycles=cooldown.match(/\b(\d+)\s*(?:cycle|day)s?\b/i)?.[1];
  return {type:MODE_SWITCH_TYPES.includes(type)?type:'CONDITION_TRIGGERED',activationCondition:clean(source.activationCondition??source.activation_condition,2000),deactivationCondition:clean(source.deactivationCondition??source.deactivation_condition,2000),cost:clean(source.cost??source.switchCost??source.switch_cost,1000),cooldown,cooldownCycles:numberOrNull(source.cooldownCycles??source.cooldown_cycles??inferredCycles),oneWay:Boolean(source.oneWay??source.one_way),permanent:Boolean(source.permanent),automatic:Boolean(source.automatic),uses:numberOrNull(source.uses??source.switchUses??source.switch_uses),targetModeIds:unique(source.targetModeIds??source.target_mode_ids)};
}

export function normalizeModeDefinition(mode={},index=0,roleId='role',abilities=[]){
  const byId=new Map(abilities.map(ability=>[String(ability.id),ability])),byName=new Map(abilities.map(ability=>[key(ability.name),ability])),name=clean(mode.name||mode.label||`Configuration ${index+1}`,120);
  const ids=(values,names=[])=>unique([...list(values),...list(names).map(value=>byName.get(key(value))?.id)]).filter(id=>byId.has(String(id))||!abilities.length);
  const abilityIds=ids(mode.abilityIds??mode.ability_ids??mode.activeAbilityIds??mode.active_ability_ids,mode.abilityNames??mode.ability_names??mode.activeAbilityNames??mode.active_ability_names),passiveAbilityIds=ids(mode.passiveAbilityIds??mode.passive_ability_ids,mode.passiveAbilityNames??mode.passive_ability_names),investigation=object(mode.investigationAppearance??mode.investigation_appearance);
  return {id:clean(mode.id||`${roleId}:mode:${slug(name)}`,160),name,description:clean(mode.description,4000),abilityIds,activeAbilityIds:abilityIds,passiveAbilityIds,immunities:unique(mode.immunities),protections:unique(mode.protections),restrictions:unique(mode.restrictions),statusBehavior:unique(mode.statusBehavior??mode.status_behavior),investigationAppearance:{basicAsk:clean(investigation.basicAsk??investigation.basic_ask,500),advancedAsk:clean(investigation.advancedAsk??investigation.advanced_ask,500),roleCheck:clean(investigation.roleCheck??investigation.role_check,500),factionAppearance:clean(investigation.factionAppearance??investigation.faction_appearance,500),roleAppearance:clean(investigation.roleAppearance??investigation.role_appearance,500),invisible:Boolean(investigation.invisible),rules:unique(investigation.rules)},cooldown:clean(mode.cooldown??mode.abilityCooldown??mode.ability_cooldown,500),abilityUses:object(mode.abilityUses??mode.ability_uses),resourcePools:object(mode.resourcePools??mode.resource_pools),switchRules:normalizeSwitchRules(mode.switchRules??mode.switch_rules??mode),specialRules:unique(mode.specialRules??mode.special_rules),sourceAbilityId:clean(mode.sourceAbilityId??mode.source_ability_id,160),sourceText:clean(mode.sourceText??mode.source_text,12000),sourceLocation:clean(mode.sourceLocation??mode.source_location,500),reviewRequired:Boolean(mode.reviewRequired??mode.review_required),reviewWarnings:unique(mode.reviewWarnings??mode.review_warnings)};
}

export function normalizeRoleModes(role={},abilities=[]){
  const byId=new Map(abilities.map(ability=>[String(ability.id),ability]));let modes=list(role.modes).map((mode,index)=>normalizeModeDefinition(mode,index,role.id||'role',abilities)).filter(mode=>mode.name);
  if(!modes.length&&abilities.length){const tagKeys=new Set(list(role.tags).map(key));modes=abilities.filter(ability=>tagKeys.has(key(ability.name))&&isModeContextAbility(ability,role)).map((ability,index)=>normalizeModeDefinition({name:clean(ability.name).replace(new RegExp('^'+clean(role.name).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*[—–-]\\s*','i'),''),sourceAbilityId:String(ability.id),sourceText:ability.sourceText||ability.definition||ability.name,sourceLocation:ability.sourceLocation||''},index,role.id||'role',abilities))}
  const seen=new Set();modes=modes.filter(mode=>{const normalized=key(mode.name);if(!normalized||seen.has(normalized))return false;seen.add(normalized);return true});
  const modeAbilityIds=new Set(modes.flatMap(mode=>[...mode.abilityIds,...mode.passiveAbilityIds]).map(String)),explicitWide=unique(role.roleWideAbilityIds??role.role_wide_ability_ids),tagKeys=new Set(list(role.tags).map(key)),derivedWide=abilities.filter(ability=>tagKeys.has(key(ability.name))&&!isModeContextAbility(ability,role)&&!modeAbilityIds.has(String(ability.id))).map(ability=>String(ability.id));
  const roleWideAbilityIds=unique(explicitWide.length?explicitWide:derivedWide).filter(id=>byId.has(String(id))||!abilities.length),roleWidePassiveAbilityIds=unique(role.roleWidePassiveAbilityIds??role.role_wide_passive_ability_ids).filter(id=>byId.has(String(id))||!abilities.length),policy=MODE_SELECTION_POLICIES.includes(String(role.modeSelectionPolicy||'').toUpperCase())?String(role.modeSelectionPolicy).toUpperCase():'CURRENT_ONLY',requestedStart=clean(role.startingModeId??role.starting_mode_id,160);
  return {modes,roleWideAbilityIds,roleWidePassiveAbilityIds,roleWideImmunities:unique(role.roleWideImmunities??role.role_wide_immunities??role.immunities),roleWideRestrictions:unique(role.roleWideRestrictions??role.role_wide_restrictions??role.restrictions),modeSelectionPolicy:policy,startingModeId:modes.some(mode=>mode.id===requestedStart)?requestedStart:modes[0]?.id||''};
}

function metadataModeIds(value={}){return unique([...(value.modeIds||value.mode_ids||[]),...(value.modeAccessIds||value.mode_access_ids||[])]);}
function accessExpired(entry,game={},at=new Date()){if(entry.expiresAt&&new Date(entry.expiresAt)<=at)return true;const cycle=Number(game.currentDay??game.currentCycle??0);if(entry.expiresCycle!=null&&cycle>Number(entry.expiresCycle))return true;if(entry.expiresCycle!=null&&cycle===Number(entry.expiresCycle)&&entry.expiresPhase&&String(game.currentPhase||'').toUpperCase()===String(entry.expiresPhase).toUpperCase()&&entry.expireOnPhaseStart!==false)return true;return false;}

export function normalizePlayerModeState(player={},role={},abilities=[]){
  const model=normalizeRoleModes(role,abilities),modeIds=new Set(model.modes.map(mode=>mode.id)),runtime=object(player.modeState??player.mode_state),requestedCurrent=clean(runtime.currentModeId??runtime.current_mode_id??player.currentModeId??player.current_mode_id,160),requestedStart=clean(runtime.startingModeId??runtime.starting_mode_id??player.startingModeId??player.starting_mode_id,160),currentModeId=modeIds.has(requestedCurrent)?requestedCurrent:(modeIds.has(requestedStart)?requestedStart:model.startingModeId);
  return {currentModeId,startingModeId:modeIds.has(requestedStart)?requestedStart:model.startingModeId,previousModeId:clean(runtime.previousModeId??runtime.previous_mode_id??player.previousModeId??player.previous_mode_id,160),modeChangedAt:runtime.changedAt??runtime.mode_changed_at??player.modeChangedAt??player.mode_changed_at??null,modeChangeReason:clean(runtime.changeReason??runtime.change_reason??player.modeChangeReason??player.mode_change_reason,1000),modeChangeSource:clean(runtime.changeSource??runtime.change_source??player.modeChangeSource??player.mode_change_source,120),modeLocked:Boolean(runtime.modeLocked??runtime.mode_locked??player.modeLocked??player.mode_locked),lockedModeId:clean(runtime.lockedModeId??runtime.locked_mode_id??player.lockedModeId??player.locked_mode_id,160),temporaryModeAccess:list(runtime.temporaryModeAccess??runtime.temporary_mode_access??player.temporaryModeAccess??player.temporary_mode_access).map(item=>typeof item==='string'?{modeId:item}:object(item)),modeCooldowns:object(runtime.modeCooldowns??runtime.mode_cooldowns??player.modeCooldowns??player.mode_cooldowns),version:Math.max(1,Number(runtime.version)||1)};
}

export function expireTemporaryModeAccess(entries=[],game={},at=new Date()){return list(entries).filter(entry=>!accessExpired(object(entry),game,at));}

export function roleModeContext({player={},role={},abilities=[],grants=[],statuses=[],selectedModeId='',game={},at=new Date()}={}){
  const model=normalizeRoleModes(role,abilities),runtime=normalizePlayerModeState(player,role,abilities),modeIds=new Set(model.modes.map(mode=>mode.id)),temporaryModeIds=new Set(expireTemporaryModeAccess(runtime.temporaryModeAccess,game,at).map(entry=>entry.modeId??entry.mode_id));
  for(const status of statuses)if(String(status.playerId??status.player_id)===String(player.id)&&String(status.state||'ACTIVE').toUpperCase()==='ACTIVE')for(const id of metadataModeIds(status.metadata||{}))if(modeIds.has(id))temporaryModeIds.add(id);
  for(const grant of grants)if(String(grant.playerId??grant.player_id)===String(player.id)&&String(grant.status||'ACTIVE').toUpperCase()==='ACTIVE')for(const id of [...metadataModeIds(grant.specialConditions??grant.special_conditions??{}),...metadataModeIds(grant.metadata||{})])if(modeIds.has(id))temporaryModeIds.add(id);
  let selected=clean(selectedModeId,160);if(!modeIds.has(selected))selected=runtime.currentModeId||model.startingModeId;const accessibleModeIds=new Set(temporaryModeIds);if(runtime.currentModeId)accessibleModeIds.add(runtime.currentModeId);if(!runtime.currentModeId&&selected)accessibleModeIds.add(selected);const switchableModeIds=new Set();if(!runtime.modeLocked&&model.modeSelectionPolicy==='CHOOSE_BEFORE_ACTION')for(const id of modeIds)if(id!==runtime.currentModeId)switchableModeIds.add(id);
  return {...model,...runtime,selectedModeId:selected,temporaryModeIds:[...temporaryModeIds].filter(id=>modeIds.has(id)),accessibleModeIds:[...accessibleModeIds],switchableModeIds:[...switchableModeIds]};
}

export function abilityModeAccess({abilityId,context}){const id=String(abilityId||''),wide=context.roleWideAbilityIds.includes(id)||context.roleWidePassiveAbilityIds.includes(id),modes=context.modes.filter(mode=>mode.abilityIds.includes(id)||mode.passiveAbilityIds.includes(id)),selectedMode=modes.find(mode=>mode.id===context.selectedModeId)||null,temporaryModes=modes.filter(mode=>context.temporaryModeIds.includes(mode.id)),currentMode=modes.find(mode=>mode.id===context.currentModeId)||null,available=wide||Boolean(currentMode)||temporaryModes.length>0,requiresSwitch=Boolean(selectedMode&&!available&&context.switchableModeIds.includes(selectedMode.id));return {available,requiresSwitch,roleWide:wide,modes,selectedMode,currentMode,temporaryModes,modeId:currentMode?.id||temporaryModes[0]?.id||selectedMode?.id||'',modeName:currentMode?.name||temporaryModes[0]?.name||selectedMode?.name||''};}

export function effectiveModeMechanics({player={},role={},abilities=[],grants=[],statuses=[],game={}}={}){const context=roleModeContext({player,role,abilities,grants,statuses,game}),activeModes=context.modes.filter(mode=>context.accessibleModeIds.includes(mode.id)),currentMode=context.modes.find(mode=>mode.id===context.currentModeId)||null;return {context,currentMode,activeModes,immunities:unique([...context.roleWideImmunities,...activeModes.flatMap(mode=>mode.immunities)]),protections:unique(activeModes.flatMap(mode=>mode.protections)),restrictions:unique([...context.roleWideRestrictions,...activeModes.flatMap(mode=>mode.restrictions)]),statusBehavior:unique(activeModes.flatMap(mode=>mode.statusBehavior)),investigationAppearance:currentMode?.investigationAppearance||{},specialRules:unique(activeModes.flatMap(mode=>mode.specialRules))};}

export function canTransitionMode({player={},role={},abilities=[],toModeId,game={},at=new Date()}={}){const context=roleModeContext({player,role,abilities,game,at}),target=context.modes.find(mode=>mode.id===String(toModeId||''));if(!target)return {allowed:false,reason:'MODE_NOT_FOUND',context};if(target.id===context.currentModeId)return {allowed:true,reason:'ALREADY_CURRENT',context,target};if(context.modeLocked)return {allowed:false,reason:'MODE_LOCKED',context,target};const cooldown=context.modeCooldowns[target.id],until=cooldown?.until??cooldown?.expiresAt??(typeof cooldown==='string'?cooldown:null),untilCycle=Number(cooldown?.untilCycle??cooldown?.until_cycle),currentCycle=Number(game.currentDay??game.currentCycle??0);if(until&&new Date(until)>at||Number.isFinite(untilCycle)&&untilCycle>currentCycle)return {allowed:false,reason:'MODE_SWITCH_COOLDOWN',context,target,availableAt:until?new Date(until).toISOString():null,availableCycle:Number.isFinite(untilCycle)?untilCycle:null};return {allowed:true,reason:'AVAILABLE',context,target};}

export function applyModeTransition({player={},role={},abilities=[],toModeId,reason='',source='GM_TRIGGERED',temporary=false,game={},at=new Date()}={}){const check=canTransitionMode({player,role,abilities,toModeId,game,at});if(!check.allowed)throw new Error(check.reason);const previous=check.context.currentModeId,target=check.target,switchRules=target.switchRules,next={...player,currentModeId:target.id,startingModeId:check.context.startingModeId,previousModeId:previous,modeChangedAt:at.toISOString(),modeChangeReason:clean(reason,1000),modeChangeSource:source,modeCooldowns:{...check.context.modeCooldowns}};if(switchRules.cooldownCycles)next.modeCooldowns[target.id]={untilCycle:Number(game.currentDay??game.currentCycle??0)+switchRules.cooldownCycles,reason:'Configuration switch cooldown'};if((switchRules.oneWay||switchRules.permanent)&&!temporary){next.modeLocked=true;next.lockedModeId=target.id}return {player:next,event:{previousModeId:previous,newModeId:target.id,previousModeName:check.context.modes.find(mode=>mode.id===previous)?.name||'',newModeName:target.name,changedAt:at.toISOString(),reason:clean(reason,1000),source,temporary,modeLocked:Boolean(next.modeLocked)}};}

export function resolveModeAwareIntel({targetPlayer={},targetRole={},abilities=[],intelType='roleCheck'}={}){const mechanics=effectiveModeMechanics({player:targetPlayer,role:targetRole,abilities}),appearance=mechanics.investigationAppearance;if(appearance.invisible)return {visible:false,result:'No result',modeId:mechanics.context.currentModeId};const property={basicAsk:'basicAsk',advancedAsk:'advancedAsk',roleCheck:'roleCheck',factionCheck:'factionAppearance'}[intelType]||intelType,result=appearance[property]||appearance.roleAppearance||appearance.factionAppearance||targetRole.name||'';return {visible:true,result,modeId:mechanics.context.currentModeId,modeName:mechanics.currentMode?.name||''};}

export function parseRoleModeAssignments(value,abilities=[],selectedAbilityIds=[]){
  const selected=new Set(selectedAbilityIds.map(String)),byName=new Map(abilities.map(ability=>[key(ability.name),ability])),modes=[],used=new Set(),errors=[];let current=null;
  const resolveNames=(raw,label)=>{const ids=[];for(const name of clean(raw,4000).split(',').map(item=>clean(item,120)).filter(Boolean)){const ability=byName.get(key(name));if(!ability){errors.push(`${current?.name||'Configuration'} references unknown ${label} "${name}".`);continue}if(!selected.has(String(ability.id))){errors.push(`Select "${ability.name}" in Role Abilities first.`);continue}if(isModeContextAbility(ability)){errors.push(`"${ability.name}" is configuration context, not an ability.`);continue}ids.push(String(ability.id));used.add(String(ability.id))}return [...new Set(ids)]};
  for(const [index,rawLine] of clean(value,24000).split(/\r?\n/).entries()){
    const line=rawLine.trim();if(!line)continue;const header=line.match(/^\[(.+)]$/);if(header){const name=clean(header[1],120);if(modes.some(mode=>key(mode.name)===key(name))){errors.push(`Configuration name "${name}" is duplicated.`);current=null;continue}current=normalizeModeDefinition({name},modes.length,'role',abilities);modes.push(current);continue}
    if(!current){const separator=line.indexOf(':');if(separator<1){errors.push(`Line ${index+1} must start a [Configuration Name] block or use "Name: Ability".`);continue}const name=clean(line.slice(0,separator),120);current=normalizeModeDefinition({name},modes.length,'role',abilities);modes.push(current);current.abilityIds=resolveNames(line.slice(separator+1),'ability');current.activeAbilityIds=current.abilityIds;continue}
    const separator=line.indexOf(':');if(separator<1){errors.push(`Line ${index+1} in ${current.name} must use "field: value".`);continue}const field=key(line.slice(0,separator)),raw=line.slice(separator+1).trim(),knownFields=new Set(['active','abilities','active abilities','passive','passives','passive abilities','description','immunities','protections','restrictions','investigation appearance','faction appearance','cooldown','switch type','switch cooldown','activation','deactivation','one way','permanent','special rules']);
    if(!knownFields.has(field)){const name=clean(line.slice(0,separator),120);if(modes.some(mode=>key(mode.name)===key(name))){errors.push(`Configuration name "${name}" is duplicated.`);current=null;continue}current=normalizeModeDefinition({name},modes.length,'role',abilities);modes.push(current);current.abilityIds=resolveNames(raw,'ability');current.activeAbilityIds=current.abilityIds;continue}
    if(['active','abilities','active abilities'].includes(field)){current.abilityIds=resolveNames(raw,'ability');current.activeAbilityIds=current.abilityIds}else if(['passive','passives','passive abilities'].includes(field))current.passiveAbilityIds=resolveNames(raw,'passive');else if(field==='description')current.description=clean(raw,4000);else if(field==='immunities')current.immunities=unique(raw.split(','));else if(field==='protections')current.protections=unique(raw.split(','));else if(field==='restrictions')current.restrictions=unique(raw.split(','));else if(field==='investigation appearance')current.investigationAppearance={...current.investigationAppearance,roleAppearance:clean(raw,500)};else if(field==='faction appearance')current.investigationAppearance={...current.investigationAppearance,factionAppearance:clean(raw,500)};else if(field==='cooldown')current.cooldown=clean(raw,500);else if(field==='switch type')current.switchRules.type=MODE_SWITCH_TYPES.includes(raw.toUpperCase())?raw.toUpperCase():'CONDITION_TRIGGERED';else if(field==='switch cooldown')current.switchRules.cooldown=clean(raw,500);else if(field==='activation')current.switchRules.activationCondition=clean(raw,2000);else if(field==='deactivation')current.switchRules.deactivationCondition=clean(raw,2000);else if(field==='one way')current.switchRules.oneWay=/^(?:true|yes|1)$/i.test(raw);else if(field==='permanent')current.switchRules.permanent=/^(?:true|yes|1)$/i.test(raw);else if(field==='special rules')current.specialRules=unique(raw.split(';'));else errors.push(`Unknown configuration field "${line.slice(0,separator).trim()}" on line ${index+1}.`);
  }
  return {modes,roleWideAbilityIds:[...selected].filter(id=>!used.has(id)),errors};
}

export function formatRoleModeAssignments(role={},abilities=[]){const byId=new Map(abilities.map(ability=>[String(ability.id),ability]));return normalizeRoleModes(role,abilities).modes.map(mode=>{const names=ids=>ids.map(id=>byId.get(String(id))?.name).filter(Boolean).join(', '),lines=[`[${mode.name}]`];if(mode.description)lines.push(`description: ${mode.description}`);lines.push(`active: ${names(mode.abilityIds)}`);if(mode.passiveAbilityIds.length)lines.push(`passive: ${names(mode.passiveAbilityIds)}`);if(mode.immunities.length)lines.push(`immunities: ${mode.immunities.join(', ')}`);if(mode.protections.length)lines.push(`protections: ${mode.protections.join(', ')}`);if(mode.investigationAppearance.roleAppearance)lines.push(`investigation appearance: ${mode.investigationAppearance.roleAppearance}`);if(mode.investigationAppearance.factionAppearance)lines.push(`faction appearance: ${mode.investigationAppearance.factionAppearance}`);if(mode.cooldown)lines.push(`cooldown: ${mode.cooldown}`);if(mode.switchRules.type!=='PLAYER_SELECTED')lines.push(`switch type: ${mode.switchRules.type}`);if(mode.switchRules.cooldown)lines.push(`switch cooldown: ${mode.switchRules.cooldown}`);if(mode.switchRules.activationCondition)lines.push(`activation: ${mode.switchRules.activationCondition}`);if(mode.switchRules.deactivationCondition)lines.push(`deactivation: ${mode.switchRules.deactivationCondition}`);if(mode.switchRules.oneWay)lines.push('one way: yes');if(mode.switchRules.permanent)lines.push('permanent: yes');if(mode.specialRules.length)lines.push(`special rules: ${mode.specialRules.join('; ')}`);return lines.join('\n')}).join('\n\n');}
