export const GLOBAL_RESOLUTION_ORDER=['BLOCKS','GUARANTEE','CONTROL','SWAPS','REDIRECTS','STATUS_EFFECTS','INTEL','CONVERTS','KILLS','DOC'] as const;
export const GLOBAL_RESOLUTION_PROFILE={schema_version:1,name:'Global Master Ability Resolution',resolution_order:GLOBAL_RESOLUTION_ORDER,passive_policy:'EVENT_TRIGGERED',heal_timing:'ANY_TIME',authority_precedence:['CURRENT_GAME_RULE','ROLE_TEXT','CURRENT_GAME_PRECEDENT','GLOBAL_MASTER_ABILITY_ENCYCLOPEDIA','GLOBAL_PRECEDENT','GM_DECISION']} as const;

const names:Record<string,{type:string;category:string;timing?:string;active_passive?:string}>={
  roleblock:{type:'Roleblock',category:'BLOCKS'},denblock:{type:'Den Block',category:'BLOCKS'},villagersblock:{type:'Villagers Block',category:'BLOCKS'},actionsuccessguarantee:{type:'Action Success Guarantee',category:'GUARANTEE'},placeswap:{type:'Place Swap',category:'SWAPS'},roleswap:{type:'Role Swap',category:'SWAPS'},redirect:{type:'Redirect',category:'REDIRECTS'},guard:{type:'Guard',category:'REDIRECTS'},reflection:{type:'Reflection',category:'PASSIVES',timing:'EVENT_TRIGGERED',active_passive:'PASSIVE'},drunk:{type:'Drunk',category:'STATUS_EFFECTS'},sober:{type:'Sober',category:'STATUS_EFFECTS'},steal:{type:'Steal',category:'STATUS_EFFECTS'},poison:{type:'Poison',category:'STATUS_EFFECTS'},mark:{type:'Mark',category:'STATUS_EFFECTS'},abilityamplify:{type:'Ability Amplify',category:'STATUS_EFFECTS'},additionaluses:{type:'Additional Uses',category:'STATUS_EFFECTS'},protect:{type:'Protect',category:'STATUS_EFFECTS'},superprotect:{type:'Super Protect',category:'STATUS_EFFECTS'},basicask:{type:'Basic Ask',category:'INTEL'},advancedask:{type:'Advanced Ask',category:'INTEL'},alignmentask:{type:'Alignment Ask',category:'INTEL'},watch:{type:'Watch',category:'INTEL'},track:{type:'Track',category:'INTEL'},actioncheck:{type:'Action Check',category:'INTEL'},gravedigger:{type:'Gravedigger',category:'INTEL'},map:{type:'Map',category:'INTEL'},convert:{type:'Convert',category:'CONVERTS'},denregularkill:{type:'Den Regular Kill',category:'KILLS'},personalinstantkill:{type:'Personal Instant Kill',category:'KILLS'},superkill:{type:'Super Kill',category:'KILLS'},omegakill:{type:'Omega Kill',category:'KILLS'},duelfight:{type:'Duel / Fight',category:'KILLS'},save:{type:'Save',category:'DOC'},heal:{type:'Heal',category:'DOC',timing:'ANY_TIME'},deathimmunity:{type:'Death Immunity',category:'PASSIVES',timing:'EVENT_TRIGGERED',active_passive:'PASSIVE'},counterattack:{type:'Counterattack',category:'PASSIVES',timing:'EVENT_TRIGGERED',active_passive:'PASSIVE'},bulletproofpassiveimmunity:{type:'Bulletproof / Passive Immunity',category:'PASSIVES',timing:'EVENT_TRIGGERED',active_passive:'PASSIVE'}
};

const key=(value:unknown)=>String(value??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');
const aliases:Record<string,string>={roleblock:'roleblock',stopaplayerfromacting:'roleblock',blocktheden:'denblock',denkill:'denregularkill',instantkill:'personalinstantkill',passiveimmunity:'bulletproofpassiveimmunity',bulletproof:'bulletproofpassiveimmunity',graveigger:'gravedigger',cleanse:'heal',swapplaces:'placeswap',swaproles:'roleswap'};

export function classifyResolutionAction(action:any,ability:any=null){
  const explicit=String(action?.resolutionCategory||action?.resolution_category||ability?.resolutionCategory||ability?.resolution_category||'').toUpperCase().replace(/[\s-]+/g,'_'),sourceKeys=[action?.standardizedAbilityType,action?.name,action?.abilityName,ability?.display_name,ability?.name,ability?.ability_id].filter(Boolean).map(key),exact=sourceKeys.map(sourceKey=>names[aliases[sourceKey]||sourceKey]).find(Boolean),semanticAlias=Object.entries(aliases).sort(([left],[right])=>right.length-left.length).find(([alias])=>sourceKeys.some(sourceKey=>sourceKey.includes(alias)))?.[1],semantic=semanticAlias?names[semanticAlias]:undefined,mapped=exact||semantic||Object.entries(names).sort(([left],[right])=>right.length-left.length).find(([candidate])=>sourceKeys.some(sourceKey=>sourceKey.includes(candidate)))?.[1],activePassive=String(action?.activePassive||action?.active_passive||mapped?.active_passive||'ACTIVE').toUpperCase()==='PASSIVE'?'PASSIVE':'ACTIVE',candidateCategory=(GLOBAL_RESOLUTION_ORDER as readonly string[]).includes(explicit)||explicit==='PASSIVES'?explicit:mapped?.category||'UNCLASSIFIED',category=activePassive==='PASSIVE'?'PASSIVES':candidateCategory,priority=category==='PASSIVES'?null:GLOBAL_RESOLUTION_ORDER.indexOf(category as any)+1||null;
  return {...action,standardizedAbilityType:action?.standardizedAbilityType||mapped?.type||action?.name||ability?.display_name||'',resolutionCategory:category,resolutionPriority:priority,resolutionTiming:category==='PASSIVES'?'EVENT_TRIGGERED':String(action?.resolutionTiming||action?.resolution_timing||mapped?.timing||'ORDERED_STAGE'),activePassive,originalTargetIds:Array.isArray(action?.originalTargetIds)?action.originalTargetIds:Array.isArray(action?.targetIds)?action.targetIds:[],effectiveTargetIds:Array.isArray(action?.effectiveTargetIds)?action.effectiveTargetIds:Array.isArray(action?.targetIds)?action.targetIds:[],transformationHistory:Array.isArray(action?.transformationHistory)?action.transformationHistory:[],generated:Boolean(action?.generated),parentActionId:String(action?.parentActionId||''),submittedAttempt:action?.submittedAttempt!==false&&!action?.generated,classificationSource:explicit?'EXPLICIT_GAME_OR_ROLE_OVERRIDE':mapped?'GLOBAL_MASTER_ABILITY_ENCYCLOPEDIA':'GM_CLASSIFICATION_REQUIRED'};
}

export function classifyAndOrderResolutionActions(actions:any[]=[]){
  const classified=actions.map((action,index)=>({...classifyResolutionAction(action),submissionIndex:index})),passives=classified.filter(action=>action.activePassive==='PASSIVE'||action.resolutionCategory==='PASSIVES'),ordered=classified.filter(action=>!passives.includes(action)).sort((a,b)=>(a.resolutionPriority??999)-(b.resolutionPriority??999)||a.submissionIndex-b.submissionIndex);
  return {ordered,passives,unclassified:classified.filter(action=>action.resolutionCategory==='UNCLASSIFIED')};
}
