import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import {effectivePlayerAbilities} from '../js/player-abilities.js';
import {analyzeDocumentBlocks} from '../js/document-import.js';
import {abilityModeAccess,applyModeTransition,canTransitionMode,effectiveModeMechanics,expireTemporaryModeAccess,formatRoleModeAssignments,isModeContextAbility,normalizeModeDefinition,normalizePlayerModeState,normalizeRoleModes,parseRoleModeAssignments,resolveModeAwareIntel,roleModeContext} from '../js/role-modes.js';

const ability=(id,name,phase='Night')=>({id,name,phase,category:phase==='Passive'?'Protection':'Support',definition:name,mechanics:[],targeting:{type:phase==='Passive'?'NO_TARGET':'ONE_PLAYER',selectionRuleType:'HARD_SELECTION_RESTRICTION',livingOnly:phase!=='Passive',selfAllowed:true,manuallyTriggerable:false}});
const abilities=[ability('strike','Strike'),ability('scan','Scan'),ability('shield','Shield','Passive'),ability('heal','Heal'),ability('phase','Phase Walk'),ability('guarantee','Action Success Guarantee'),ability('roleblock','Roleblock')];
const modes=[
  {id:'r:calm',name:'Calm Shell',description:'A guarded state.',abilityIds:['scan'],passiveAbilityIds:['shield'],immunities:['Poison'],protections:['Normal Kill'],restrictions:['Cannot attack'],investigationAppearance:{roleAppearance:'Civilian',factionAppearance:'Town'},switchRules:{type:'PLAYER_SELECTED'}},
  {id:'r:war',name:'War Shape',abilityIds:['strike'],passiveAbilityIds:[],immunities:['Roleblock'],protections:['Super Kill'],restrictions:[],investigationAppearance:{roleAppearance:'Warrior',factionAppearance:'Den'},abilityUses:{strike:{baseUses:2,sharedPool:'power'}},resourcePools:{power:{uses:2,sharedAcrossModes:true}},switchRules:{type:'PLAYER_SELECTED',cooldown:'1 cycle'}},
  {id:'r:ghost',name:'Ghost Protocol',abilityIds:['phase'],passiveAbilityIds:[],immunities:['Kill'],protections:[],restrictions:['No communication'],investigationAppearance:{invisible:true},switchRules:{type:'CONDITION_TRIGGERED',activationCondition:'After death',oneWay:true,permanent:true}}
];
const role={id:'r',name:'Sentinel',roleType:'STANDARD',tags:abilities.map(item=>item.name),modes,roleWideAbilityIds:['heal','guarantee','roleblock'],roleWidePassiveAbilityIds:[],roleWideImmunities:['Conversion'],roleWideRestrictions:['Cannot self-target'],startingModeId:'r:calm',modeSelectionPolicy:'CHOOSE_BEFORE_ACTION'};
const effective=(player,selectedModeId='',statuses=[])=>effectivePlayerAbilities({player,role,abilities,statuses,grants:[],resolutionEvents:[],roleModifiers:[],game:{currentDay:2,currentPhase:'Night'},selectedModeId});

test('configuration 1: arbitrary source names are preserved exactly',()=>assert.deepEqual(normalizeRoleModes(role,abilities).modes.map(item=>item.name),['Calm Shell','War Shape','Ghost Protocol']));
test('configuration 2: roles support three configurations',()=>assert.equal(normalizeRoleModes(role,abilities).modes.length,3));
test('configuration 3: roles support more than three configurations',()=>assert.equal(normalizeRoleModes({...role,modes:[...modes,{name:'Fourth Unnamed Form'}]},abilities).modes.length,4));
test('configuration 4: a role-wide active is available in every configuration',()=>{for(const selected of modes.map(item=>item.id))assert.equal(effective({id:'p',currentModeId:'r:calm'},selected).abilities.find(item=>item.abilityId==='heal')?.available,true)});
test('configuration 5: role-wide passive identifiers stay separate',()=>assert.deepEqual(normalizeRoleModes({...role,roleWidePassiveAbilityIds:['shield']},abilities).roleWidePassiveAbilityIds,['shield']));
test('configuration 6: current configuration exposes its active ability',()=>assert.ok(effective({id:'p',currentModeId:'r:calm'}).abilities.some(item=>item.abilityId==='scan')));
test('configuration 7: current configuration exposes its passive mechanic',()=>assert.equal(effective({id:'p',currentModeId:'r:calm'}).abilities.find(item=>item.abilityId==='shield')?.passive,true));
test('configuration 8: inactive configuration rejects its ability under current-only policy',()=>{const result=effectivePlayerAbilities({player:{id:'p',currentModeId:'r:calm'},role:{...role,modeSelectionPolicy:'CURRENT_ONLY'},abilities,game:{currentDay:2,currentPhase:'Night'},selectedModeId:'r:war'}),strike=result.abilities.find(item=>item.abilityId==='strike');assert.equal(strike.available,false);assert.ok(strike.reasons.includes('INACTIVE_MODE'))});
test('configuration 9: selectable alternate configuration is marked as requiring a switch',()=>{const context=roleModeContext({player:{id:'p',currentModeId:'r:calm'},role,abilities,selectedModeId:'r:war'});assert.equal(abilityModeAccess({abilityId:'strike',context}).requiresSwitch,true)});
test('configuration 10: temporary access exposes both current and temporary abilities',()=>{const result=effective({id:'p',currentModeId:'r:calm',temporaryModeAccess:[{modeId:'r:war'}]});assert.ok(result.abilities.some(item=>item.abilityId==='scan'));assert.ok(result.abilities.some(item=>item.abilityId==='strike'))});
test('configuration 11: expired temporary access is removed',()=>assert.deepEqual(expireTemporaryModeAccess([{modeId:'r:war',expiresAt:'2026-01-01T00:00:00Z'}],{},new Date('2026-02-01T00:00:00Z')),[]));
test('configuration 12: role-wide and current immunities combine',()=>assert.deepEqual(effectiveModeMechanics({player:{currentModeId:'r:calm'},role,abilities}).immunities,['Conversion','Poison']));
test('configuration 13: immunity changes after a transition',()=>{const moved=applyModeTransition({player:{currentModeId:'r:calm'},role,abilities,toModeId:'r:war',reason:'Damage threshold met'}).player;assert.deepEqual(effectiveModeMechanics({player:moved,role,abilities}).immunities,['Conversion','Roleblock'])});
test('configuration 14: protections change with the current configuration',()=>assert.deepEqual(effectiveModeMechanics({player:{currentModeId:'r:war'},role,abilities}).protections,['Super Kill']));
test('configuration 15: restrictions combine role-wide and configuration-specific rules',()=>assert.deepEqual(effectiveModeMechanics({player:{currentModeId:'r:calm'},role,abilities}).restrictions,['Cannot self-target','Cannot attack']));
test('configuration 16: investigation uses the current configuration appearance',()=>assert.equal(resolveModeAwareIntel({targetPlayer:{currentModeId:'r:war'},targetRole:role,abilities,intelType:'roleCheck'}).result,'Warrior'));
test('configuration 17: invisible configuration returns no investigation result',()=>assert.equal(resolveModeAwareIntel({targetPlayer:{currentModeId:'r:ghost'},targetRole:role,abilities}).visible,false));
test('configuration 18: manual transition records previous, new, reason, source, and timestamp',()=>{const result=applyModeTransition({player:{currentModeId:'r:calm'},role,abilities,toModeId:'r:war',reason:'GM approved',source:'GM_TRIGGERED',at:new Date('2026-08-28T12:00:00Z')});assert.deepEqual([result.event.previousModeId,result.event.newModeId,result.event.reason,result.event.source,result.event.changedAt],['r:calm','r:war','GM approved','GM_TRIGGERED','2026-08-28T12:00:00.000Z'])});
test('configuration 19: a permanent one-way transition locks the destination',()=>{const result=applyModeTransition({player:{currentModeId:'r:war'},role,abilities,toModeId:'r:ghost',reason:'Death trigger'});assert.equal(result.player.modeLocked,true);assert.equal(canTransitionMode({player:result.player,role,abilities,toModeId:'r:calm'}).reason,'MODE_LOCKED')});
test('configuration 20: a future switch cooldown blocks transition',()=>assert.equal(canTransitionMode({player:{currentModeId:'r:calm',modeCooldowns:{'r:war':{until:'2027-01-01T00:00:00Z'}}},role,abilities,toModeId:'r:war',at:new Date('2026-08-28T00:00:00Z')}).reason,'MODE_SWITCH_COOLDOWN'));
test('configuration 21: structured role editor parses active, passive, defenses, appearance, cooldown, and switch rules',()=>{const parsed=parseRoleModeAssignments('[Prism State]\ndescription: refracts attacks\nactive: Strike, Scan\npassive: Shield\nimmunities: Poison\nprotections: Super Kill\nrestrictions: No speech\ninvestigation appearance: Glass Knight\nfaction appearance: Neutral\ncooldown: 2 cycles\nswitch type: DAMAGE_TRIGGERED\nswitch cooldown: 1 cycle\nactivation: After damage\none way: yes\nspecial rules: Keep shared uses',abilities,abilities.map(item=>item.id)),mode=parsed.modes[0];assert.deepEqual(parsed.errors,[]);assert.equal(mode.name,'Prism State');assert.deepEqual(mode.abilityIds,['strike','scan']);assert.deepEqual(mode.passiveAbilityIds,['shield']);assert.equal(mode.switchRules.type,'DAMAGE_TRIGGERED');assert.equal(mode.switchRules.oneWay,true);assert.equal(mode.investigationAppearance.roleAppearance,'Glass Knight')});
test('configuration 22: legacy Name: Ability syntax remains compatible',()=>assert.deepEqual(parseRoleModeAssignments('Sun Form: Strike\nMoon Form: Scan',abilities,['strike','scan']).modes.map(item=>item.name),['Sun Form','Moon Form']));
test('configuration 23: formatted blocks preserve exact custom names and mechanics',()=>{const text=formatRoleModeAssignments(role,abilities);assert.match(text,/\[Ghost Protocol\]/);assert.match(text,/activation: After death/);assert.match(text,/permanent: yes/)});
test('configuration 24: duplicate configuration names are rejected case-insensitively',()=>assert.match(parseRoleModeAssignments('[Alpha]\nactive: Strike\n[alpha]\nactive: Scan',abilities,['strike','scan']).errors.join(' '),/duplicated/i));
test('configuration 25: ordinary abilities are not mistaken for configuration records',()=>assert.equal(isModeContextAbility(ability('mode-shift','Mode Shift')),false));
test('configuration 26: explicit configuration records can never be actions',()=>assert.equal(isModeContextAbility({...ability('context','Any Name'),recordType:'MODE_CONTEXT',selectableAsAction:false}),true));
test('configuration 27: player runtime state normalizes snake-case database fields',()=>{const state=normalizePlayerModeState({mode_state:{current_mode_id:'r:war',previous_mode_id:'r:calm',mode_locked:false,temporary_mode_access:[{modeId:'r:ghost'}]}},role,abilities);assert.equal(state.currentModeId,'r:war');assert.equal(state.previousModeId,'r:calm');assert.equal(state.temporaryModeAccess[0].modeId,'r:ghost')});
test('configuration 28: Roleblock and Action Success Guarantee remain status warnings, not silent configuration loss',()=>{const statuses=[{playerId:'p',state:'ACTIVE',statusType:'ROLEBLOCK',statusName:'Roleblocked'},{playerId:'p',state:'ACTIVE',statusType:'ACTION_SUCCESS_GUARANTEE',statusName:'Guaranteed'}],result=effective({id:'p',currentModeId:'r:calm'},'',statuses);assert.deepEqual(result.warnings,['Roleblocked','Guaranteed']);assert.ok(result.abilities.some(item=>item.abilityId==='scan'))});
test('configuration 29: production SQL persists state, history, temporary access, locks, and pre-action switches safely',()=>{const sql=readFileSync(new URL('../supabase/migrations/20260828080000_global_role_configurations.sql',import.meta.url),'utf8');for(const required of ['player_mode_states','player_mode_events','temporary_mode_access','mode_locked','MODE_SWITCH_COOLDOWN','requiresSwitch','PLAYER_SELECTED','change_player_mode'])assert.match(sql,new RegExp(required));assert.match(sql,/action_player_id text/);assert.match(sql,/grant_source\.player_id=action_player_id/)});
test('configuration 30: UI exposes manual change, temporary access, configuration history, and switch-before-action language',()=>{const app=readFileSync(new URL('../js/app.js',import.meta.url),'utf8'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8');for(const label of ['Change Configuration','Temporary Access','Configuration history','Switch before action'])assert.match(app,new RegExp(label,'i'));assert.match(html,/CONFIGURATION CONTEXT/);assert.match(html,/forms \/ states/)});
test('configuration 31: both AI endpoints receive current configuration semantics',()=>{const importer=readFileSync(new URL('../supabase/functions/gm-document-import/index.ts',import.meta.url),'utf8'),copilot=readFileSync(new URL('../supabase/functions/gm-copilot/index.ts',import.meta.url),'utf8');assert.match(importer,/alternative configurations/i);assert.match(importer,/hierarchy/i);assert.match(copilot,/current configuration/i);assert.match(copilot,/temporary access/i)});
test('configuration 32: normalization does not rewrite source-defined configuration names into a fixed vocabulary',()=>{const custom=normalizeModeDefinition({name:'The Court Is In Session'},0,'judge',abilities);assert.equal(custom.name,'The Court Is In Session');assert.doesNotMatch(custom.name,/robot|vehicle|human/i)});
test('configuration 33: document hierarchy creates custom configurations and nests mechanics correctly',()=>{const heading=(level,text)=>({type:'heading',level,text}),blocks=[heading(1,'Custom Game'),heading(1,'Factions'),heading(2,'Town'),heading(3,'Shifter'),heading(4,'Calm Shell'),{type:'list-item',indent:1,text:'Ability: Scan — inspect one player'},{type:'list-item',indent:1,text:'Immunity: Poison'},heading(4,'War Shape'),{type:'list-item',indent:1,text:'Ability: Strike — attack one player'}],parsed=analyzeDocumentBlocks(blocks,{fileName:'custom.docx'}),parsedRole=parsed.roles[0];assert.deepEqual(parsedRole.modes.map(item=>item.name),['Calm Shell','War Shape']);assert.deepEqual(parsedRole.modes[0].abilityNames,['Scan']);assert.deepEqual(parsedRole.modes[0].immunities,['Poison']);assert.deepEqual(parsedRole.modes[1].abilityNames,['Strike'])});
test('configuration 34: entering a configuration creates its cycle cooldown automatically',()=>{const result=applyModeTransition({player:{currentModeId:'r:calm'},role,abilities,toModeId:'r:war',reason:'Switch',game:{currentDay:4}});assert.equal(result.player.modeCooldowns['r:war'].untilCycle,5)});
test('configuration 35: approved MODE_CHANGE effects are applied through the audited resolution transaction',()=>{const sql=readFileSync(new URL('../supabase/migrations/20260828080000_global_role_configurations.sql',import.meta.url),'utf8'),copilot=readFileSync(new URL('../supabase/functions/gm-copilot/index.ts',import.meta.url),'utf8');assert.match(sql,/upper\(coalesce\(value->>'type',''\)\)='MODE_CHANGE'/);assert.match(sql,/resolutionSessionId/);assert.match(sql,/private\.approve_and_apply_resolution/);assert.match(sql,/private\.change_player_mode_state/);assert.match(copilot,/concrete persistent configuration change/)});
